# Generated by Django 4.2.13 on 2024-07-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_buyerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
