# Generated by Django 4.2.13 on 2024-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default='DRAFT', max_length=15, null=True),
        ),
    ]
