# Generated by Django 4.2.13 on 2024-06-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_c_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='c_status',
            new_name='status',
        ),
    ]
