# Generated by Django 4.2.13 on 2024-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_c_status_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default='DRAFT', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('IN STOCK', 'In Stock'), ('OUT OF STOCK', 'Out of Stock')], default='OUT OF STOCK', max_length=15, null=True),
        ),
    ]
