# Generated by Django 4.2.13 on 2024-06-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('products', '0005_product_status_alter_product_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_products', to='dashboard.district'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_products', to='dashboard.region'),
        ),
    ]
